apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rylangraham02-dev

namePrefix: prod-

commonLabels:
  environment: prod

resources:
  - ../../base

images:
  - name: ghcr.io/ronaldsg20/mdas-ci-practice
    newTag: latest

replicas:
  - name: mdas-ci-practice
    count: 3
