apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rylangraham02-dev

namePrefix: prod-green-

commonLabels:
  environment: prod-green

resources:
  - ../../base

images:
  - name: ghcr.io/ronaldsg20/mdas-ci-practice
    newTag: latest

patches:
  - path: route-patch.yaml
    target:
      kind: Route
      name: mdas-ci-practice

replicas:
  - name: mdas-ci-practice
    count: 3
