apiVersion: v1
kind: Service
metadata:
  name: mdas-ci-practice
  labels:
    app: mdas-ci-practice
spec:
  selector:
    app: mdas-ci-practice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
