apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rylangraham02-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: ghcr.io/ronaldsg20/mdas-ci-practice
    newTag: develop

replicas:
  - name: mdas-ci-practice
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "development"
    target:
      kind: Deployment
      name: mdas-ci-practice
