apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rylangraham02-dev

namePrefix: dev-

commonLabels:
  environment: dev

resources:
  - ../../base

images:
  - name: ghcr.io/ronaldsg20/mdas-ci-practice
    newTag: develop

patches:
  - path: route-patch.yaml
    target:
      kind: Route
      name: mdas-ci-practice
